---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Provision a VPC
    ec2_vpc:
       state: present
       cidr_block: 172.22.0.0/16
       resource_tags: { "Environment":"Development" }
       subnets:
         - cidr: 172.22.1.0/24
           az: eu-west-1c
           resource_tags: { "Environment":"Dev", "Tier" : "Web" }
         - cidr: 172.22.2.0/24
           az: eu-west-1b
           resource_tags: { "Environment":"Dev", "Tier" : "App" }
         - cidr: 172.22.3.0/24
           az: eu-west-1a
           resource_tags: { "Environment":"Dev", "Tier" : "DB" }
       internet_gateway: True
       route_tables:
         - subnets:
           - 172.22.2.0/24
           - 172.22.3.0/24
           routes:
           - dest: 0.0.0.0/0
             gw: igw
         - subnets:
           - 172.22.1.0/24
           routes:
           - dest: 0.0.0.0/0
           gw: igw
       region: eu-west-1
    register: vpc
